
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
# from POST_proceso import *
import POST_proceso as pp
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button, PhotoImage
from tkinter import filedialog,simpledialog



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH =   Path(str(OUTPUT_PATH)+r"\assets\frame0")
# INIT_PATH   =   OUTPUT_PATH.parent.parent
INIT_PATH   =  OUTPUT_PATH



def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("667x435")
window.configure(bg = "#FFFFFF")
window.title("Módulo de Mantenimiento Predictivo")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 435,
    width = 667,
    bd = 0,
    highlightthickness = 0,
    # relief = "ridge"
    # relief = "flat"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    333.0,
    217.0,
    image=image_image_1
)

canvas.create_text(
    30.0,
    18.0,
    anchor="nw",
    text="Bienvenido al procesador de mediciones",
    fill="#000000",
    font=("Thabit Bold", 14 * -1)
)

canvas.create_text(
    384.0,
    423.0,
    anchor="nw",
    text="Hecho para Colbún en la central Nehuenco. @NVP",
    fill="#000000",
    font=("Thabit Bold", 10 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    # command=lambda: print("button_1 clicked"),

    command     =lambda:
        [pp.ejecutar(
        filedialog.askopenfilename(
            initialdir = INIT_PATH,
            title = "Select file",
            filetypes = (("csv files","*.csv"),("all files","*.*"))))
         
         ]
        ,        
    # command     =lambda: pp.ejecutar(
    #     filedialog.askopenfilename(
    #         initialdir = INIT_PATH,
    #         title = "Select file",
    #         filetypes = (("csv files","*.csv"),("all files","*.*")))),
    relief="flat"
)
button_1.place(
    x=30.0,
    y=46.0,
    width=130.0,
    height=30.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    #command=lambda: print("button_2 clicked"),
    command=lambda: pp.comparar_PSD(
        simpledialog.askinteger(
            "Comparar FFT's", "N° de archivos a comparar")),
    relief="flat",
    #state="disabled"
)
button_2.place(
    x=186.0,
    y=46.0,
    width=130.0,
    height=30.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    # command=lambda: print("button_3 clicked"),
    command=lambda: pp.low_freq_fft(
        filedialog.askopenfilename(
            initialdir = INIT_PATH,
            title = "Select file",
            filetypes = (("csv files","*.csv"),("all files","*.*")))),
    relief="flat",
    # state="disabled"
)
button_3.place(
    x=30.0,
    y=90.0,
    width=130.0,
    height=30.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    # command=lambda: print("button_4 clicked"),
    command=lambda: pp.high_freq_fft(
        filedialog.askopenfilename(
            initialdir = INIT_PATH,
            title = "Select file",
            filetypes = (("csv files","*.csv"),("all files","*.*")))),
    relief="flat",
    # state="disabled"
)
button_4.place(
    x=185.0,
    y=90.0,
    width=130.0,
    height=30.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    # command=lambda: print("button_5 clicked"),
    command=lambda: pp.PSD(
        filedialog.askopenfilename(
            initialdir = INIT_PATH,
            title = "Select file",
            filetypes = (("csv files","*.csv"),("all files","*.*")))),
    relief="flat",
    # state="disabled"
)
button_5.place(
    x=30.0,
    y=134.0,
    width=130.0,
    height=30.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat",
    state="disabled"
)
button_6.place(
    x=184.0,
    y=134.0,
    width=130.0,
    height=30.0
)

# button_image_7 = PhotoImage(
#     file=relative_to_assets("button_7.png"))
# button_7 = Button(
#     image=button_image_7,
#     borderwidth=0,
#     highlightthickness=0,
#     command=lambda: print("button_7 clicked"),
#     relief="flat",
#     state="disabled"
# )
# button_7.place(
#     x=31.0,
#     y=178.0,
#     width=130.0,
#     height=30.0
# )

window.resizable(False, False)
window.mainloop()
